# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stat.proto',
  package='main',
  syntax='proto3',
  serialized_pb=_b('\n\nstat.proto\x12\x04main\"\xb5\x01\n\nCephStatus\x12\x0e\n\x06Status\x18\x01 \x01(\r\x12\r\n\x05UsedG\x18\x02 \x01(\r\x12\r\n\x05\x46reeG\x18\x03 \x01(\r\x12\r\n\x05\x44\x61taG\x18\x04 \x01(\r\x12\x0f\n\x07ReadBPS\x18\x05 \x01(\r\x12\x10\n\x08WriteBPS\x18\x06 \x01(\r\x12\x0f\n\x07ReadsPS\x18\x07 \x01(\r\x12\x10\n\x08WritesPS\x18\x08 \x01(\r\x12\x13\n\x0bOsdMapEpoch\x18\t \x01(\r\x12\x0f\n\x07OsdLats\x18\n \x03(\r\"R\n\x0b\x43\x65phOpsLats\x12\r\n\x05RSize\x18\x01 \x01(\r\x12\x10\n\x08RSkipped\x18\x02 \x01(\r\x12\x10\n\x08WSkipped\x18\x03 \x01(\r\x12\x10\n\x08LatHisto\x18\x04 \x03(\r\"@\n\x08\x43\x65phInfo\x12\x12\n\nCompressed\x18\x01 \x01(\x08\x12\x0f\n\x07OsdDump\x18\x02 \x01(\x0c\x12\x0f\n\x07OsdTree\x18\x03 \x01(\x0c\"\xac\x01\n\x0c\x43\x65phSettings\x12\x0f\n\x07\x43luster\x18\x01 \x01(\t\x12\x13\n\x0bHistoryTime\x18\x02 \x01(\r\x12\x13\n\x0bHistorySize\x18\x03 \x01(\r\x12\x1a\n\x12LatsCollectTimeout\x18\x04 \x01(\r\x12\x10\n\x08HistoMin\x18\x05 \x01(\r\x12\x10\n\x08HistoMax\x18\x06 \x01(\r\x12\x11\n\tHistoBins\x18\x07 \x01(\r\x12\x0e\n\x06OsdIDS\x18\x08 \x03(\r\"\x07\n\x05\x45mpty\"\x1b\n\x0b\x43lusterName\x12\x0c\n\x04Name\x18\x01 \x01(\t2\x97\x02\n\tSensorRPC\x12\x30\n\rGetCephStatus\x12\x0b.main.Empty\x1a\x10.main.CephStatus\"\x00\x12\x32\n\x0bGetCephInfo\x12\x11.main.ClusterName\x1a\x0e.main.CephInfo\"\x00\x12;\n\x16SetupLatencyMonitoring\x12\x12.main.CephSettings\x1a\x0b.main.Empty\"\x00\x12\x32\n\x0eGetCephOpsLats\x12\x0b.main.Empty\x1a\x11.main.CephOpsLats\"\x00\x12\x33\n\x15StopLatencyMonitoring\x12\x0b.main.Empty\x1a\x0b.main.Empty\"\x00\x62\x06proto3')
)




_CEPHSTATUS = _descriptor.Descriptor(
  name='CephStatus',
  full_name='main.CephStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='main.CephStatus.Status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UsedG', full_name='main.CephStatus.UsedG', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FreeG', full_name='main.CephStatus.FreeG', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DataG', full_name='main.CephStatus.DataG', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ReadBPS', full_name='main.CephStatus.ReadBPS', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WriteBPS', full_name='main.CephStatus.WriteBPS', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ReadsPS', full_name='main.CephStatus.ReadsPS', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WritesPS', full_name='main.CephStatus.WritesPS', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OsdMapEpoch', full_name='main.CephStatus.OsdMapEpoch', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OsdLats', full_name='main.CephStatus.OsdLats', index=9,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=202,
)


_CEPHOPSLATS = _descriptor.Descriptor(
  name='CephOpsLats',
  full_name='main.CephOpsLats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RSize', full_name='main.CephOpsLats.RSize', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RSkipped', full_name='main.CephOpsLats.RSkipped', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WSkipped', full_name='main.CephOpsLats.WSkipped', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LatHisto', full_name='main.CephOpsLats.LatHisto', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=286,
)


_CEPHINFO = _descriptor.Descriptor(
  name='CephInfo',
  full_name='main.CephInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Compressed', full_name='main.CephInfo.Compressed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OsdDump', full_name='main.CephInfo.OsdDump', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OsdTree', full_name='main.CephInfo.OsdTree', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=352,
)


_CEPHSETTINGS = _descriptor.Descriptor(
  name='CephSettings',
  full_name='main.CephSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cluster', full_name='main.CephSettings.Cluster', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HistoryTime', full_name='main.CephSettings.HistoryTime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HistorySize', full_name='main.CephSettings.HistorySize', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LatsCollectTimeout', full_name='main.CephSettings.LatsCollectTimeout', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HistoMin', full_name='main.CephSettings.HistoMin', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HistoMax', full_name='main.CephSettings.HistoMax', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HistoBins', full_name='main.CephSettings.HistoBins', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OsdIDS', full_name='main.CephSettings.OsdIDS', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=527,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='main.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=536,
)


_CLUSTERNAME = _descriptor.Descriptor(
  name='ClusterName',
  full_name='main.ClusterName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='main.ClusterName.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=565,
)

DESCRIPTOR.message_types_by_name['CephStatus'] = _CEPHSTATUS
DESCRIPTOR.message_types_by_name['CephOpsLats'] = _CEPHOPSLATS
DESCRIPTOR.message_types_by_name['CephInfo'] = _CEPHINFO
DESCRIPTOR.message_types_by_name['CephSettings'] = _CEPHSETTINGS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ClusterName'] = _CLUSTERNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CephStatus = _reflection.GeneratedProtocolMessageType('CephStatus', (_message.Message,), dict(
  DESCRIPTOR = _CEPHSTATUS,
  __module__ = 'stat_pb2'
  # @@protoc_insertion_point(class_scope:main.CephStatus)
  ))
_sym_db.RegisterMessage(CephStatus)

CephOpsLats = _reflection.GeneratedProtocolMessageType('CephOpsLats', (_message.Message,), dict(
  DESCRIPTOR = _CEPHOPSLATS,
  __module__ = 'stat_pb2'
  # @@protoc_insertion_point(class_scope:main.CephOpsLats)
  ))
_sym_db.RegisterMessage(CephOpsLats)

CephInfo = _reflection.GeneratedProtocolMessageType('CephInfo', (_message.Message,), dict(
  DESCRIPTOR = _CEPHINFO,
  __module__ = 'stat_pb2'
  # @@protoc_insertion_point(class_scope:main.CephInfo)
  ))
_sym_db.RegisterMessage(CephInfo)

CephSettings = _reflection.GeneratedProtocolMessageType('CephSettings', (_message.Message,), dict(
  DESCRIPTOR = _CEPHSETTINGS,
  __module__ = 'stat_pb2'
  # @@protoc_insertion_point(class_scope:main.CephSettings)
  ))
_sym_db.RegisterMessage(CephSettings)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'stat_pb2'
  # @@protoc_insertion_point(class_scope:main.Empty)
  ))
_sym_db.RegisterMessage(Empty)

ClusterName = _reflection.GeneratedProtocolMessageType('ClusterName', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERNAME,
  __module__ = 'stat_pb2'
  # @@protoc_insertion_point(class_scope:main.ClusterName)
  ))
_sym_db.RegisterMessage(ClusterName)



_SENSORRPC = _descriptor.ServiceDescriptor(
  name='SensorRPC',
  full_name='main.SensorRPC',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=568,
  serialized_end=847,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCephStatus',
    full_name='main.SensorRPC.GetCephStatus',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CEPHSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCephInfo',
    full_name='main.SensorRPC.GetCephInfo',
    index=1,
    containing_service=None,
    input_type=_CLUSTERNAME,
    output_type=_CEPHINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetupLatencyMonitoring',
    full_name='main.SensorRPC.SetupLatencyMonitoring',
    index=2,
    containing_service=None,
    input_type=_CEPHSETTINGS,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCephOpsLats',
    full_name='main.SensorRPC.GetCephOpsLats',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CEPHOPSLATS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopLatencyMonitoring',
    full_name='main.SensorRPC.StopLatencyMonitoring',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORRPC)

DESCRIPTOR.services_by_name['SensorRPC'] = _SENSORRPC

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SensorRPCStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetCephStatus = channel.unary_unary(
          '/main.SensorRPC/GetCephStatus',
          request_serializer=Empty.SerializeToString,
          response_deserializer=CephStatus.FromString,
          )
      self.GetCephInfo = channel.unary_unary(
          '/main.SensorRPC/GetCephInfo',
          request_serializer=ClusterName.SerializeToString,
          response_deserializer=CephInfo.FromString,
          )
      self.SetupLatencyMonitoring = channel.unary_unary(
          '/main.SensorRPC/SetupLatencyMonitoring',
          request_serializer=CephSettings.SerializeToString,
          response_deserializer=Empty.FromString,
          )
      self.GetCephOpsLats = channel.unary_unary(
          '/main.SensorRPC/GetCephOpsLats',
          request_serializer=Empty.SerializeToString,
          response_deserializer=CephOpsLats.FromString,
          )
      self.StopLatencyMonitoring = channel.unary_unary(
          '/main.SensorRPC/StopLatencyMonitoring',
          request_serializer=Empty.SerializeToString,
          response_deserializer=Empty.FromString,
          )


  class SensorRPCServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetCephStatus(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetCephInfo(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SetupLatencyMonitoring(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetCephOpsLats(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StopLatencyMonitoring(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SensorRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetCephStatus': grpc.unary_unary_rpc_method_handler(
            servicer.GetCephStatus,
            request_deserializer=Empty.FromString,
            response_serializer=CephStatus.SerializeToString,
        ),
        'GetCephInfo': grpc.unary_unary_rpc_method_handler(
            servicer.GetCephInfo,
            request_deserializer=ClusterName.FromString,
            response_serializer=CephInfo.SerializeToString,
        ),
        'SetupLatencyMonitoring': grpc.unary_unary_rpc_method_handler(
            servicer.SetupLatencyMonitoring,
            request_deserializer=CephSettings.FromString,
            response_serializer=Empty.SerializeToString,
        ),
        'GetCephOpsLats': grpc.unary_unary_rpc_method_handler(
            servicer.GetCephOpsLats,
            request_deserializer=Empty.FromString,
            response_serializer=CephOpsLats.SerializeToString,
        ),
        'StopLatencyMonitoring': grpc.unary_unary_rpc_method_handler(
            servicer.StopLatencyMonitoring,
            request_deserializer=Empty.FromString,
            response_serializer=Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'main.SensorRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSensorRPCServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetCephStatus(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetCephInfo(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SetupLatencyMonitoring(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetCephOpsLats(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StopLatencyMonitoring(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSensorRPCStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetCephStatus(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetCephStatus.future = None
    def GetCephInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetCephInfo.future = None
    def SetupLatencyMonitoring(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SetupLatencyMonitoring.future = None
    def GetCephOpsLats(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetCephOpsLats.future = None
    def StopLatencyMonitoring(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    StopLatencyMonitoring.future = None


  def beta_create_SensorRPC_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('main.SensorRPC', 'GetCephInfo'): ClusterName.FromString,
      ('main.SensorRPC', 'GetCephOpsLats'): Empty.FromString,
      ('main.SensorRPC', 'GetCephStatus'): Empty.FromString,
      ('main.SensorRPC', 'SetupLatencyMonitoring'): CephSettings.FromString,
      ('main.SensorRPC', 'StopLatencyMonitoring'): Empty.FromString,
    }
    response_serializers = {
      ('main.SensorRPC', 'GetCephInfo'): CephInfo.SerializeToString,
      ('main.SensorRPC', 'GetCephOpsLats'): CephOpsLats.SerializeToString,
      ('main.SensorRPC', 'GetCephStatus'): CephStatus.SerializeToString,
      ('main.SensorRPC', 'SetupLatencyMonitoring'): Empty.SerializeToString,
      ('main.SensorRPC', 'StopLatencyMonitoring'): Empty.SerializeToString,
    }
    method_implementations = {
      ('main.SensorRPC', 'GetCephInfo'): face_utilities.unary_unary_inline(servicer.GetCephInfo),
      ('main.SensorRPC', 'GetCephOpsLats'): face_utilities.unary_unary_inline(servicer.GetCephOpsLats),
      ('main.SensorRPC', 'GetCephStatus'): face_utilities.unary_unary_inline(servicer.GetCephStatus),
      ('main.SensorRPC', 'SetupLatencyMonitoring'): face_utilities.unary_unary_inline(servicer.SetupLatencyMonitoring),
      ('main.SensorRPC', 'StopLatencyMonitoring'): face_utilities.unary_unary_inline(servicer.StopLatencyMonitoring),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_SensorRPC_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('main.SensorRPC', 'GetCephInfo'): ClusterName.SerializeToString,
      ('main.SensorRPC', 'GetCephOpsLats'): Empty.SerializeToString,
      ('main.SensorRPC', 'GetCephStatus'): Empty.SerializeToString,
      ('main.SensorRPC', 'SetupLatencyMonitoring'): CephSettings.SerializeToString,
      ('main.SensorRPC', 'StopLatencyMonitoring'): Empty.SerializeToString,
    }
    response_deserializers = {
      ('main.SensorRPC', 'GetCephInfo'): CephInfo.FromString,
      ('main.SensorRPC', 'GetCephOpsLats'): CephOpsLats.FromString,
      ('main.SensorRPC', 'GetCephStatus'): CephStatus.FromString,
      ('main.SensorRPC', 'SetupLatencyMonitoring'): Empty.FromString,
      ('main.SensorRPC', 'StopLatencyMonitoring'): Empty.FromString,
    }
    cardinalities = {
      'GetCephInfo': cardinality.Cardinality.UNARY_UNARY,
      'GetCephOpsLats': cardinality.Cardinality.UNARY_UNARY,
      'GetCephStatus': cardinality.Cardinality.UNARY_UNARY,
      'SetupLatencyMonitoring': cardinality.Cardinality.UNARY_UNARY,
      'StopLatencyMonitoring': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'main.SensorRPC', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
